/** @type {import('tailwindcss').Config} */

module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: "class",
  theme: {
    colors: {
      // Using modern `rgb`
      primary: "#ff0000",
      white: "#ffffff",
      black: "#000000",
      blue: "#61a7d6",
      background: "#e0b88b",
      foreground: "#d4d4c4",
      break: "#d9d9d9",
      holiday: "#000000",
      arcColors: {
        romanceDawn: "#ff0000",
        orangeTown: "#ff7f00",
        syrupVillage: "#79653e",
        baratie: "#ffff00",
        arlongPark: "	#5d8aa8",
        loguetown: "#fffacd",
        reverseMountain: "#ffbb99",
        whiskeyPeak: "#ff9966",
        littleGarden: "#c3f733",
        drumIsland: "#ffb7c5",
        arabasta: "#802b00",
        jaya: "#52fafa",
        skypiea: "#cdfefe",
        longRingLongLand: "#b3d1ff",
        water7: "#4d94ff",
        eniesLobby: "#0047b3",
        postEnisLobby: "#003380",
        thrillerBark: "#730099",
        sabaodyArchipelago: " #ccffcc",
        amazonLily: "#33ff33",
        impelDown: "#00b359",
        marineford: "#99ff99",
        postWar: "#b5e3b5",
        returnToSabaody: "#9fd592",
        fishmanIsland: "#99ddff",
        punkHazard: "#cc99ff",
        dressrosa: "#ff69b4",
        zou: "#8cff66",
        wholeCakeIsland: "#fba0e3",
        levely: "#ff6666",
        wanoCountry: "#ffff66",
        eggheadIsland: "#2eb5f3",
      },
    },
  },
  plugins: [],
};
